import 'package:flutter/material.dart';
import 'package:flutterapp/zomato1app/generatedrestaurantwidget/generated/GeneratedFoodItemsWidget.dart';
import 'package:flutterapp/zomato1app/generatedrestaurantwidget/generated/GeneratedFooterWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/zomato1app/generatedrestaurantwidget/generated/GeneratedHeaderWidget1.dart';

/* Frame Restaurant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRestaurantWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 411.0,
        height: 823.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 6.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 661.0,
                child: GeneratedFoodItemsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0056084031896289;

                  final double height =
                      constraints.maxHeight * 0.09658193298562329;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.012267697466550952,
                        y: constraints.maxHeight * -0.006469734673946191,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedHeaderWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 1.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 62.0,
                child: GeneratedFooterWidget1(),
              )
            ]),
      ),
    ));
  }
}
