import 'package:flutter/material.dart';
import 'package:flutterapp/zomato1app/generatedhomewidget2/generated/GeneratedFooterWidget2.dart';
import 'package:flutterapp/zomato1app/generatedhomewidget2/generated/GeneratedRetaurantsWidget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 411.0,
        height: 823.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 725.0,
                child: GeneratedRetaurantsWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 62.0,
                child: GeneratedFooterWidget2(),
              )
            ]),
      ),
    ));
  }
}
